### ISSUE TITLE
Installing Helm via curl fails if using sh

### ISSUE THREAD

**Issue by joreize** [nicholasdille/packages#43]
I tried installing helm using curl like recommended in your readme
``` curl -s https://pkg.dille.io/helm/install.sh | sh ```

and got the following error:
```sh: 5: Syntax error: "(" unexpected```

If I'm using bash instead of sh everything works fine
```curl -s https://pkg.dille.io/helm/install.sh | bash```

**Comment by nicholasdille** [comment]
The documentation incorrectly explains to pipe to `sh`. The old instructions were able to run in `sh` but since I converted them to functions you must pipe them to `bash`. I will update the documentation accordingly!

**Comment by nicholasdille** [comment]
See #42
