### ISSUE TITLE
java needs docker running

### ISSUE THREAD

**Issue by joreize** [nicholasdille/packages#492]
When i tried to install java, i got an error-message that docker isn't running. please add this to requirenments :-) 

![grafik](https://user-images.githubusercontent.com/34373288/100348695-8c233300-2fe7-11eb-8fc7-4ba04a58eb1d.png)

the output at the end doesnt display the installed version correctly 

![grafik](https://user-images.githubusercontent.com/34373288/100348846-cf7da180-2fe7-11eb-8df1-a510aba71431.png)

**Comment by nicholasdille** [comment]
Thanks for your feedback. I have modified java (and jabba) to not require a Docker daemon because they don't ;-)

**Comment by nicholasdille** [comment]
I am relying on renovate to update versions and I have yet to find a repository to track versions of openjdk

**Comment by nicholasdille** [comment]
Updating java version is tracked in #493
